packages:
  - apps/*
  - packages/*
  - services/*
  - shared/*
YAMLpkg update -y && pkg install -y nodejs-lts git
npm i -g pnpm

cd ~/createxyz-project

# Root package.json (if missing)
cat > package.json << 'JSON'
{
  "name": "createxyz-project",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev:web": "pnpm --filter web dev",
    "dev:mobile": "pnpm --filter mobile start",
    "build:web": "pnpm --filter web build",
    "lint": "pnpm -r lint"
  }
}
JSON

# Workspace map
cat > pnpm-workspace.yaml << 'YAML'
packages:
  - apps/*
  - packages/*
  - services/*
  - shared/*
YAMLpkg update -y && pkg install -y nodejs-lts git
npm i -g pnpm

cd ~/createxyz-project

# Root package.json (if missing)
cat > package.json << 'JSON'
{
  "name": "createxyz-project",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev:web": "pnpm --filter web dev",
    "dev:mobile": "pnpm --filter mobile start",
    "build:web": "pnpm --filter web build",
    "lint": "pnpm -r lint"
  }
}
JSON

# Workspace map
cat > pnpm-workspace.yaml << 'YAML'
packages:
  - apps/*
  - packages/*
  - services/*
  - shared/*
